Revert "HBASE-12558 TestHCM.testClusterStatus Unexpected exception, expected<org.apache.hadoop.hbase.regionserver.RegionServerStoppedException> but was<junit.framework.AssertionFailedError> -- ADDED DEBUG"
Accidental commit. Reverting.

This reverts commit 23dcb0efa011179c9487165f0bf5edf981df12db [formerly 2458be08ed894c33bea48983e3fe390dbbb0fe28].


Former-commit-id: b8ab1b176cfa6e5898f6aedea3c2d7af1fa92675