Revert "HBASE-12558 TestHCM.testClusterStatus Unexpected exception, expected<org.apache.hadoop.hbase.regionserver.RegionServerStoppedException> but was<junit.framework.AssertionFailedError> -- ADDED DEBUG"
This reverts commit 2314575783934e1f7430ed001f9049912ce34eaa [formerly 8b8f2026bda6a329d6d82376dbb884c8f183a967].

Overcommit. Added "HBASE-12490 Replace uses of setAutoFlush(boolean,
boolean)" by mistake

Conflicts:
	hbase-client/src/main/java/org/apache/hadoop/hbase/client/ClusterStatusListener.java
	hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java

Former-commit-id: 1a9b556474d01480762bf8df431c499443d24737