HBASE-18803: Mapreduce job get failed caused by NoClassDefFoundError: org/apache/commons/lang3/ArrayUtils
Signed-off-by: Michael Stack <stack@apache.org>

Former-commit-id: e10d7836ed420754fcf13e3ab7ea1c1c2f1c2098