HBASE-8482 TestHBaseFsck#testCheckTableLocks broke; java.lang.AssertionError: expected:<[]> but was:<[EXPIRED_TABLE_LOCK]>
git-svn-id: https://svn.apache.org/repos/asf/hbase/trunk@1478556 13f79535-47bb-0310-9956-ffa450edef68

Former-commit-id: 1a516ff5b78b87909aa7fbbd1ea4eda08e53fc92